package provenance

import (
	"fmt"
	"strings"

	"github.com/ramKarthik57/provenancex/internal/artifact"
	"github.com/ramKarthik57/provenancex/internal/repository"
)

// Verifier checks provenance statements against actual artifacts and repository states
type Verifier struct {
	allowedBuilders map[string]bool
}

// NewVerifier constructs a provenance verifier
func NewVerifier(allowedBuilders []string) *Verifier {
	builders := map[string]bool{
		DefaultBuilderID: true,
	}
	for _, b := range allowedBuilders {
		builders[strings.TrimSpace(b)] = true
	}
	return &Verifier{
		allowedBuilders: builders,
	}
}

// Verify checks whether an in-toto SLSA statement is consistent with actual observed artifact and repository
func (v *Verifier) Verify(stmt *InTotoStatement, art *artifact.Metadata, repo *repository.State) *VerificationResult {
	res := &VerificationResult{
		Valid:          true,
		Contradictions: []*Contradiction{},
		BuilderID:      stmt.Predicate.RunDetails.Builder.ID,
		BuildType:      stmt.Predicate.BuildDefinition.BuildType,
		SubjectCount:   len(stmt.Subject),
	}

	// 1. Verify Artifact Digest
	if art != nil {
		foundSubject := false
		for _, subj := range stmt.Subject {
			// Match by name or single subject
			if strings.EqualFold(subj.Name, art.Name) || len(stmt.Subject) == 1 {
				foundSubject = true
				claimedSHA, hasSHA := subj.Digest["sha256"]
				if !hasSHA {
					res.Valid = false
					res.Contradictions = append(res.Contradictions, &Contradiction{
						Field:       "subject.digest.sha256",
						Claimed:     "(none)",
						Observed:    art.SHA256,
						Description: fmt.Sprintf("Provenance subject for %q does not provide a sha256 digest", subj.Name),
					})
				} else if !strings.EqualFold(claimedSHA, art.SHA256) {
					res.Valid = false
					res.Contradictions = append(res.Contradictions, &Contradiction{
						Field:       "subject.digest.sha256",
						Claimed:     claimedSHA,
						Observed:    art.SHA256,
						Description: fmt.Sprintf("ARTIFACT HASH CONTRADICTION: Provenance claims artifact hash %s, but actual artifact is %s", claimedSHA, art.SHA256),
					})
				}
				break
			}
		}

		if !foundSubject {
			res.Valid = false
			res.Contradictions = append(res.Contradictions, &Contradiction{
				Field:       "subject",
				Claimed:     fmt.Sprintf("%v", stmt.Subject),
				Observed:    art.Name,
				Description: fmt.Sprintf("Artifact %q is missing from provenance subjects list", art.Name),
			})
		}
	}

	// 2. Verify Material Commit SHA
	if repo != nil && repo.CommitSHA != "" {
		for _, dep := range stmt.Predicate.BuildDefinition.ResolvedDependencies {
			for alg, digest := range dep.Digest {
				if strings.Contains(strings.ToLower(alg), "sha") {
					// Check if commit SHA matches
					if !strings.EqualFold(digest, repo.CommitSHA) {
						res.Valid = false
						res.Contradictions = append(res.Contradictions, &Contradiction{
							Field:       "materials.digest",
							Claimed:     digest,
							Observed:    repo.CommitSHA,
							Description: fmt.Sprintf("SOURCE COMMIT CONTRADICTION: Provenance claims source commit %s, but repository is at commit %s", digest, repo.CommitSHA),
						})
					}
				}
			}
		}
	}

	// 3. Verify Builder ID
	if res.BuilderID != "" && len(v.allowedBuilders) > 0 {
		if !v.allowedBuilders[res.BuilderID] {
			res.Valid = false
			res.Contradictions = append(res.Contradictions, &Contradiction{
				Field:       "builder.id",
				Claimed:     res.BuilderID,
				Observed:    "allowed-builders-policy",
				Description: fmt.Sprintf("Provenance was generated by untrusted builder %q", res.BuilderID),
			})
		}
	}

	return res
}
