package day17

// BuildClaimInventory constructs the audited classification inventory for claims C1 through C10
func BuildClaimInventory() []*ClaimInventoryRow {
	return []*ClaimInventoryRow{
		{
			ClaimID:                "C1",
			ClaimShortName:         "Detection Capability & Recall",
			TargetLayer:            "Cross-Layer Decision Engine (All 12 Layers)",
			OriginalClaimStatement: "ProvenanceX achieves 100% false-positive free detection of software supply-chain attacks across all attack vectors.",
			AuditedClassification:  "PARTIALLY_VALIDATED",
			OperationalBoundary:    "Achieves 98.75% attack recall post-remediation (vs. 80.00% pre-remediation on Day 12). 0% false positives observed across evaluated 1,000 trials when in-tree generated path exemptions are declared. Detection requires active multi-layer evidence; out-of-boundary activity is undetectable.",
			DemonstratedFailure:    "Demonstrated failure on ADV-HUNT-01 (filesystem modification outside monitored workspace root boundary), ADV-HUNT-03 (sub-10ms ephemeral process in user-mode), and ADV-HUNT-05 (dictionary-word subdomain tunneling).",
			EmpiricalEvidenceRef:   "results/day12_baseline/adversarial_campaign_raw.csv, results/day13/per_family.csv, results/day16/blind_spot_matrix.csv",
		},
		{
			ClaimID:                "C2",
			ClaimShortName:         "Detection Latency vs Build Overhead",
			TargetLayer:            "Telemetry & Decision Engine",
			OriginalClaimStatement: "Sub-millisecond (12.4 µs) supply-chain attack detection latency with negligible runtime overhead.",
			AuditedClassification:  "BOUNDED",
			OperationalBoundary:    "Pure in-memory cross-layer evidence correlation requires 12.4 µs (mean). However, end-to-end physical build overhead is 0.24% (~2.4 ms on standard compilation). Disk streaming hash verification on large artifacts (>100MB) incurs up to 48.2 ms.",
			DemonstratedFailure:    "Equating pure algorithmic in-memory correlation speed with total end-to-end build wall-clock overhead is invalid. Disk I/O dominates physical artifact hashing.",
			EmpiricalEvidenceRef:   "results/day15/end_to_end.csv, results/day15/performance_summary.csv, results/day16/performance.csv",
		},
		{
			ClaimID:                "C3",
			ClaimShortName:         "Graph & Ingestion Scalability",
			TargetLayer:            "Layer 2 (Trust Graph) & Dependency Ingestion",
			OriginalClaimStatement: "Linear or sub-linear O(1)/O(N) computational and memory scaling across arbitrary graph scales and dependency depths.",
			AuditedClassification:  "VALIDATED",
			OperationalBoundary:    "Empirically validated up to 1,000 artifacts, 500 dependencies, and 10,000 evidence nodes. In-memory graph topological construction and validation scales linearly at 4.8 µs per node with peak memory <24 MB.",
			DemonstratedFailure:    "Unbounded reachability queries without topological sort caching would exhibit O(V^3) latency on dense graphs.",
			EmpiricalEvidenceRef:   "results/day15/artifact_benchmark.csv, results/day15/dependency_benchmark.csv, results/day15/graph_benchmark.csv",
		},
		{
			ClaimID:                "C4",
			ClaimShortName:         "Trust Graph DAG & Lineage Localization",
			TargetLayer:            "Layer 2 (Trust Graph & Evidence Lineage)",
			OriginalClaimStatement: "Guarantees acyclic evidence lineage DAG and uniquely localizes the root-cause layer of any supply-chain tampering.",
			AuditedClassification:  "VALIDATED",
			OperationalBoundary:    "Strict DAG acyclicity verified across all 1,000 trials. Root cause isolation accurately pinpoints the lowest topological layer where evidence requirements fail.",
			DemonstratedFailure:    "Simultaneous multi-layer tampering localizes the earliest topological violation rather than reporting all independent disjoint forks unless multi-root traversal is enabled.",
			EmpiricalEvidenceRef:   "results/day14/raw_trials.csv (COMPOSED_ATTACK 100% layer attribution), internal/graph/graph_test.go",
		},
		{
			ClaimID:                "C5",
			ClaimShortName:         "Temporal Consistency Forensics",
			TargetLayer:            "Layer 5 (Temporal Consistency Analysis)",
			OriginalClaimStatement: "Detects all temporal ordering anomalies, causal inversions, and retroactive evidence modifications.",
			AuditedClassification:  "BOUNDED",
			OperationalBoundary:    "Detects commit timestamp backdating, retroactive evidence modification, and out-of-order build stages within the resolution of host monotonic clocks.",
			DemonstratedFailure:    "Sub-millisecond clock skew between distributed asynchronous CI runners cannot be distinguished from causal inversion without synchronized PTP/hardware timestamping.",
			EmpiricalEvidenceRef:   "internal/temporal/temporal_test.go, results/day12_baseline/adversarial_per_family.csv",
		},
		{
			ClaimID:                "C6",
			ClaimShortName:         "Binary Structural Forensics",
			TargetLayer:            "Layer 9 (Binary Structural Forensics)",
			OriginalClaimStatement: "Comprehensive PE/ELF structural forensic detection of section entropy anomalies, header tampering, and debug signature stripping.",
			AuditedClassification:  "VALIDATED",
			OperationalBoundary:    "Validates PE/COFF and ELF headers, section entropy (detecting packed/encrypted code >7.2 Shannon entropy), debug directory matching, and Authenticode/digital signatures.",
			DemonstratedFailure:    "Low-entropy code injections or padding-manipulated polyglot payloads that mimic legitimate compiler section structures can evade static entropy thresholds.",
			EmpiricalEvidenceRef:   "internal/forensics/binary_test.go",
		},
		{
			ClaimID:                "C7",
			ClaimShortName:         "Air-Gapped Standalone Offline Verifier",
			TargetLayer:            "Standalone Verification Binary (provenancex-verifier)",
			OriginalClaimStatement: "Deterministic, standalone evidence bundle verification with zero database and zero network dependencies.",
			AuditedClassification:  "VALIDATED",
			OperationalBoundary:    "Air-gapped verification binary operates with zero network sockets and zero external dependencies. Cryptographically validates tar.gz archives, SHA-256 manifests, Ed25519/ECDSA/RSA signatures, and in-toto SLSA attestations.",
			DemonstratedFailure:    "Verification cannot dynamically query online Certificate Revocation Lists (CRLs) or Rekor transparency logs without violating air-gapped isolation.",
			EmpiricalEvidenceRef:   "cmd/provenancex-verifier/main.go, results/day17/offline_verifier_audit.csv",
		},
		{
			ClaimID:                "C8",
			ClaimShortName:         "Runtime Telemetry Observability Boundary",
			TargetLayer:            "Layers 6, 7, 8 (Process, Filesystem, Network Telemetry)",
			OriginalClaimStatement: "Complete runtime observability of all build-time processes, filesystem modifications, and network connections.",
			AuditedClassification:  "BOUNDED",
			OperationalBoundary:    "Complete 100% event capture is achieved only with Windows Administrator privileges via Kernel ETW providers. User-mode fallback relies on process polling and directory change notifications.",
			DemonstratedFailure:    "In unprivileged user-mode CI runners, sub-10ms ephemeral processes (ADV-HUNT-03) and rapid create-and-delete transient file races (ADV-HUNT-04) evade capture.",
			EmpiricalEvidenceRef:   "results/day16/process_visibility.csv, results/day16/filesystem_visibility.csv, results/day17/observability_audit.csv",
		},
		{
			ClaimID:                "C9",
			ClaimShortName:         "Adversarial Generalization & Composed Attacks",
			TargetLayer:            "Adversarial Evaluation Subsystem",
			OriginalClaimStatement: "Guarantees 100% detection of unseen supply-chain attack vectors and multi-stage composed mutations.",
			AuditedClassification:  "PARTIALLY_VALIDATED",
			OperationalBoundary:    "Evaluated across 11 unseen attack scenarios (5,500 trials) and 3 composed multi-layer attack scenarios (750 trials) with 100% recall on the evaluated suites.",
			DemonstratedFailure:    "Does not generalize to attacks operating entirely outside configured workspace paths or low-entropy dictionary-word subdomain tunneling.",
			EmpiricalEvidenceRef:   "results/day14/raw_trials.csv, results/day16/adversarial_reattack.csv, results/day16/blind_spot_matrix.csv",
		},
		{
			ClaimID:                "C10",
			ClaimShortName:         "Benign Operational Stability & False Alarms",
			TargetLayer:            "Policy & Decision Subsystem",
			OriginalClaimStatement: "Zero false positives across all software development workflows and real-world build systems.",
			AuditedClassification:  "BOUNDED",
			OperationalBoundary:    "Zero false positives (0/1,000 trials, 100% specificity) observed on standard builds when legitimate in-tree generated files (e.g. mock_*.go, protobuf, swagger) are declared in policy.",
			DemonstratedFailure:    "Default strict repository cleanliness policy triggers false positives if code generation tools write untracked files without declared path exemptions (BENIGN-HUNT-04).",
			EmpiricalEvidenceRef:   "results/day16/benign_campaign.csv, results/day16/policy_eval.csv",
		},
	}
}
